site: Ilya Semenov
title: Ilya Semenov
description: >-
  I am a Data Science student with a strong passion for data and artificial intelligence. 
  During my spare time I devour books and I always try to study and learn new things. 
  I am fascinated by the world of productivity and investements. 
  Well, I wish I have 48 hours per day, but I have to settle for 24!
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: Europe/Moscow
repo: https://github.com/Ilsolang/Ilsolang.github.io # site repo [optional]
data-theme: light # default theme "dark" | "light"

author:
  name: Ilya Semenov
  bio: 
  username: Ilsolang # general username
  github: Ilsolang # github username
  twitter: Ilsolang # twitter username
  email: essilyasemenov@gmail.com # email adress

# URL settings
url: "https://ilsolang.github.io/" # Domain Name of host. [username].github.io for github pages
baseurl: # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


